spring:
   datasource:
      username: pet_store
      password: pet_store
      url: jdbc:mysql://localhost:3307/pet_store
   jpa:
      hibernate:
         ddl-auto: create
      show-sql: true